import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-screen max-h-screen max-w-screen-4xl min-h-[800px] w-screen min-w-[800px] select-none">
        <main className="flex h-full w-full">{children}</main>
        <Toaster position="bottom-right" />
      </body>
    </html>
  );
}
